### PR TITLE
Simple implementation with backend and data persistence into a JSON file

### PR DESCRIPTION
**Pull request by devmao**
Please check the README file for more info.

### CODE REVIEW

**Comment by devmao** [comment]
Unfortunately, I didn't have time for testing it on other browsers than Google Chrome 62.x.

**Comment by jindrichsamec** [comment]
Thanks Maurizio for your PR. Code looks good, but I didn't find any test. There was one in original repository and you've removed it. Why? :)

**Comment by devmao** [comment]
Hi @jindrichsamec, I'm a big fan of tests :) but I'm still working on it in my spare time that is really little in these days.
I will try to complete them soon if they are still relevant to you. Thanks.

**Comment by jindrichsamec** [comment]
Thanks @devmao, great job! :) Looking forward to lunch..

**Pull request closed without merging**
